language: c
sudo: false
services: docker

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh

script:
  - bash ./.travis-docker.sh

env:
  global:
    - PACKAGE="owl" GIT_MERGE_VERBOSITY=0
  matrix:
    - DISTRO=ubuntu-14.04 OCAML_VERSION=4.06.0 # match opam-repository travis
